# Generated by Django 4.1.6 on 2023-02-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="locationverification",
            options={"verbose_name_plural": "LocationVerification"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(upload_to="profile_pictures"),
        ),
    ]
