# Generated by Django 4.1.6 on 2023-02-06 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_trustlevel_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="content",
        ),
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/profile"),
        ),
        migrations.AlterField(
            model_name="trustlevel",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trust_level",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
