# Generated by Django 4.1.6 on 2023-02-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="topic_type",
            field=models.IntegerField(
                choices=[
                    (1, "Text"),
                    (2, "User"),
                    (3, "Post Sobun"),
                    (4, "Post Event"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
