# Generated by Django 4.1.6 on 2023-02-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobunpost",
            name="picture",
            field=models.ImageField(upload_to="post_pictures"),
        ),
    ]
