# Generated by Django 4.1.6 on 2023-02-09 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobunrate",
            name="sobun",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate",
                to="app.sobun",
            ),
        ),
    ]
