# Generated by Django 4.1.6 on 2023-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_goodscategory_created_at_goodscategory_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobunpost",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
