# Generated by Django 4.1.6 on 2023-02-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_sobunpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sobunpost",
            name="place",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sobunpost",
            name="product",
            field=models.CharField(max_length=100),
        ),
    ]
